---
- name: Add nginx, nodejs, postgres sources
  apt_repository:
    repo: '{{ item.repo }}'
    state: present
    filename: '{{ item.filename }}'
  with_items:
    - { repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }} trusty main', filename: 'nodesource' }
    - { repo: 'deb-src https://deb.nodesource.com/node_{{ nodejs_version }} trusty main', filename: 'nodesource' }
    - { repo: 'ppa:nginx/stable', filename: 'nginx' }
    - { repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main', filename: 'pgdg' }
  become: yes

- name: Add apt signing key for nodejs, postgres
  apt_key:
    url: '{{ item.url }}'
    state: present
  with_items:
    - { url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key' }
    - { url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc' }
  become: yes

- name: Install nginx, nodejs, postgres
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: present
  with_items:
    - nodejs
    - nginx
    - postgresql-{{ postgres_version }}
  become: yes

- name: Install erlang {{ erlang_version }}
  apt:
    deb: "http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_{{ erlang_version }}~ubuntu~trusty_amd64.deb" #debian~jessie_amd64.deb
    state: present
    force: yes
  become: yes
  tags: url

- name: Install elixir elixir_version
  apt:
    deb: "http://packages.erlang-solutions.com/site/ec/elixir/FLAVOUR_2_download/elixir_{{ elixir_version }}~ubuntu~trusty_amd64.deb"
    state: present
    force: yes
  become: yes
  tags: url

- name: Install prerequisites for database
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
  tags: try

- name: clone TWChennai/RecruitX-Backend
  git:
    repo: https://github.com/TWChennai/RecruitX-Backend.git
    dest: $HOME/RecruitX-Backend
    clone: yes
    update: yes
    #version: "{{ custom-deployment }}"
  tags: repo


- name: Create database
  postgresql_db: name="{{ database_name }}" encoding="UTF-8"
  become: yes
  become_user: postgres
  tags: try

- name: Rec_Install local hex
  command: " bash -ilc 'mix local.hex --force' "
  args:
    chdir: ~/RecruitX-Backend
    executable: /bin/bash
  tags: bash

- name: Rec_Install mix deps
  command: "bash -ilc 'mix deps.get --force'"
  args:
    chdir: ~/RecruitX-Backend
    executable: /bin/bash

- name: Rec_Install local_rebar
  command: "bash -ilc 'mix local.rebar --force'"
  args:
    chdir: ~/RecruitX-Backend
    executable: /bin/bash

- name: Rec_create vagarant role
  command: psql -U postgres -c "CREATE ROLE \"vagrant\" LOGIN CREATEDB;"
  become: yes
  become_user: postgres

- name: Rec_mix ecto.create db
  command: "bash -ilc 'mix ecto.create'"
  args:
    chdir: ~/RecruitX-Backend
    executable: /bin/bash

- name: Rec_Start phoenix server
  command: "bash -ilc 'mix phoenix.server'"
  args:
    chdir: ~/RecruitX-Backend
    executable: /bin/bash
