---
  # - name: set timezone to Asia/Kolkata
  #     timezone: Asia/Kolkata
  #   when: "{{ ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' }}"
  #   become: yes
  #   tags: system_setup

  - name: Setup Hostname App01
    hostname:
      name: app011
    become: yes
    tags: system_setup
    when: "{{ ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' }}"

  - name: Disable Selinux
    selinux:
      state: disabled
    when: not "{{ ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' }}"
    become: yes
    tags: system_setup
